export const ALTER_MAIN_PAGE = 'ALTER_MAIN_PAGE';
export const USER_LOGIN = 'USER_LOGIN';
export const TOGGLE_DAY = 'TOGGLE_DAY';
export const CHANGE_JOB_NAME = 'CHANGE_JOB_NAME';
export const ADD_JOB = 'ADD_JOB';
export const DELETE_JOB = 'DELETE_JOB';
export const CHANGE_TIME = 'CHANGE_TIME';
export const ADD_GENERAL_GROUP = 'ADD_GENERAL_GROUP';
export const DELETE_GENERAL_GROUP = 'DELETE_GENERAL_GROUP';
export const ADD_COMPONENT = 'ADD_COMPONENT';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const CHANGE_COMPONENT_NAME = 'CHANGE_COMPONENT_NAME';
export const CHANGE_COMPONENT_NODE = 'CHANGE_COMPONENT_NODE';
export const CHANGE_COMPONENT_PORT = 'CHANGE_COMPONENT_PORT';
export const CHANGE_NAME_ICON = 'CHANGE_NAME_ICON';
export const CHANGE_TYPE_VALUE = 'CHANGE_TYPE_VALUE';
export const CHANGE_TYPE_IO = 'CHANGE_TYPE_IO';

